# Workflow of this goal is to lint the code like to check syntax error, formatting and identation. 

name: Lint

on: 
  push:
    paths: "*.jsx"

jobs:
  code-lint:
    name: Run Oxlint
    runs-on: ubuntu-latest
    steps:
      - name: Chekout or clone the code
        uses: actions/checkout@v7            

        # Runs natively via npx WITHOUT local npm install or package.json setup
      - name: Run Oxlint Binary
        run: npx oxlint@latest --deny-jsx-a11y
    
    
